
package org.donstu.async;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CynologyService", targetNamespace = "https://donstu.org/cynology")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CynologyService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<org.donstu.async.GetDogsResponse>
     */
    @WebMethod(operationName = "getDogs")
    @RequestWrapper(localName = "getDogs", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogs")
    @ResponseWrapper(localName = "getDogsResponse", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogsResponse")
    public Response<GetDogsResponse> getDogsAsync();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getDogs")
    @RequestWrapper(localName = "getDogs", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogs")
    @ResponseWrapper(localName = "getDogsResponse", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogsResponse")
    public Future<?> getDogsAsync(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetDogsResponse> asyncHandler);

    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.async.Dog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDogs", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogs")
    @ResponseWrapper(localName = "getDogsResponse", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.async.GetDogsResponse")
    @Action(input = "https://donstu.org/cynology/CynologyService/getDogsRequest", output = "https://donstu.org/cynology/CynologyService/getDogsResponse")
    public List<Dog> getDogs();

}
