
package org.donstu.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CynologyService", targetNamespace = "https://donstu.org/cynology")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CynologyService {


    /**
     * 
     * @return
     *     returns java.util.List<org.donstu.client.Dog>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDogs", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.client.GetDogs")
    @ResponseWrapper(localName = "getDogsResponse", targetNamespace = "https://donstu.org/cynology", className = "org.donstu.client.GetDogsResponse")
    @Action(input = "https://donstu.org/cynology/CynologyService/getDogsRequest", output = "https://donstu.org/cynology/CynologyService/getDogsResponse")
    public List<Dog> getDogs();

}
